spring.datasource.url=jdbc:postgresql://fraud-flagger-db.csx8oqw88sp9.us-east-1.rds.amazonaws.com:5432/fraudflagger
spring.datasource.username=postgres
spring.datasource.password=sasuke13581
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.h2.console.enabled=false